require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'spec/internal/bin/*'
    - 'spec/internal/db/schema.rb'

Metrics/LineLength:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/PredicateName:
  Exclude:
    - spec/services/tempfile_service_spec.rb

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/units/config_spec.rb
    - spec/units/transcoding_spec.rb

RSpec/AnyInstance:
  Exclude:
    - spec/processors/image_spec.rb
    - spec/units/transcoding_spec.rb
