require 'spec_helper'

describe Hydra::Derivatives::Image do
  let(:object) { ActiveFedora::Base.new }
  describe "when arguments are passed as a string" do
    let(:directives) {{ :thumb => "100x100>" } }
    subject { Hydra::Derivatives::Image.new(object, 'content', directives)}

    it "should use the string as the size and the name is autogenerated" do
      expect(subject).to receive(:create_resized_image).with(an_instance_of(ActiveFedora::Datastream), "100x100>", 'png') do |ds|
        expect(ds.dsid).to eq('content_thumb')
      end
      subject.process
    end
  end
  describe "when arguments are passed as a hash" do
    let(:directives) {{ :thumb => {size: "200x300>", datastream: 'thumbnail'} }}
    subject { Hydra::Derivatives::Image.new(object, 'content', directives)}
    it "should use the specified size and name" do
      expect(subject).to receive(:create_resized_image).with(an_instance_of(ActiveFedora::Datastream), "200x300>", 'png') do |ds|
        expect(ds.dsid).to eq('thumbnail')
      end
      subject.process

    end
  end
end
