require 'spec_helper'

describe Hydra::Derivatives::Image do
  let(:object) { ActiveFedora::Base.new }
  let(:output_file) { double }

  subject { Hydra::Derivatives::Image.new(object, 'content', directives)}

  before { expect(subject).to receive(:output_file).with(file_name).and_return(output_file) }

  describe "when arguments are passed as a string" do
    let(:directives) { { thumb: "100x100>" } }
    let(:file_name) { 'content_thumb' }

    it "should use the string as the size and the name is autogenerated" do
      expect(subject).to receive(:create_resized_image).with(output_file, "100x100>", 'png')
      subject.process
    end
  end

  describe "when arguments are passed as a hash" do
    let(:directives) { { thumb: { size: "200x300>", datastream: file_name } } }
    let(:file_name) { 'thumbnail' }

    it "should use the specified size and name" do
      expect(subject).to receive(:create_resized_image).with(output_file, "200x300>", 'png')
      subject.process
    end
  end
end
